# Form implementation generated from reading ui file './app/ui/templates/main.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 542)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuColumn = QtWidgets.QMenu(parent=self.menuEdit)
        self.menuColumn.setObjectName("menuColumn")
        self.menuRow = QtWidgets.QMenu(parent=self.menuEdit)
        self.menuRow.setObjectName("menuRow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionAdd_One = QtGui.QAction(parent=MainWindow)
        self.actionAdd_One.setObjectName("actionAdd_One")
        self.actionAdd_One_2 = QtGui.QAction(parent=MainWindow)
        self.actionAdd_One_2.setObjectName("actionAdd_One_2")
        self.menuFile.addAction(self.actionSave_as)
        self.menuColumn.addAction(self.actionAdd_One)
        self.menuRow.addAction(self.actionAdd_One_2)
        self.menuEdit.addAction(self.menuColumn.menuAction())
        self.menuEdit.addAction(self.menuRow.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuColumn.setTitle(_translate("MainWindow", "&Column"))
        self.menuRow.setTitle(_translate("MainWindow", "&Row"))
        self.actionSave_as.setText(_translate("MainWindow", "&Save As ..."))
        self.actionAdd_One.setText(_translate("MainWindow", "&Add"))
        self.actionAdd_One_2.setText(_translate("MainWindow", "&Add"))
